# ------------------------------------- #
# ---- General Settings --------------- #
# ------------------------------------- #
baseURL = "https://www.kohsruhe.com/"
title = "Kohsruhe"
theme = "den"
enableRobotsTXT = true      # generate robots.txt
enableEmoji = true           # use emoji support
hasCJKLanguage = true        # detect CJK languages for word count etc.
preserveTaxonomyNames = true # do not make tag names lowercase
# uglyURLs = true            # more info: https://gohugo.io/content-management/urls/#ugly-urls
rssLimit = 100                # limit number of entries in RSS feeds
page_view_conter = true

# Copyright, appears in the footer
# copyright = ""             # default: author.name

# Pagination
# number of entries per page for archives, tags and categories
# since we don't have list view, recommend a large value
paginate = 20
paginatePath = "page"

# Syntax Hightlight
PygmentsCodeFences = true
PygmentsUseClasses = true    # required for shhighlight shortcode

# service plugins
disqusShortname = ""         # disqus_shortname
googleAnalytics = ""         # UA-XXXXXXXX-X

# language support # en / zh / other... translations present in i18n/
defaultContentLanguage = "zh"           # Default language to use
defaultContentLanguageInSubdir = true

# Links format
[permalinks]
  posts = "/:year/:month/:day/:filename/"
  categories = "/category/:slug/"      # required
  tags = "/tag/:slug/"                # required
  pages = "/:slug/"

[author]                     # required
  name = "Leehyon HNG"

[sitemap]                    # required
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# ------------------------------------- #
# ---- Other Params ------------------- #
# ------------------------------------- #

[params]
  since = "2022"             # Site creation time
  rssFullContent = true      # set true to use full content instead of summary

  # site info (optional)
  keywords = ["hugo","embedded","programming"]
  description = "When I was seven I thought I had caught the cicada named Summer."
  logoTitle = "Koh" # shown on top-left, default: title
  siteLogoImage = "images/noble.png"     # shown besides logoTitle
  # headerTitle = "Koh"                   # default: title
  headerImage = "images/lake.jpeg"
  showAuthorCard = true # Whether to show author information below the article

  showMenuLanguages = true

  autoLoadComments = false # auto load comment when scrolling down

  # paginate style, default use numbered pagination links
  # if true, use original "Previous" and "Next" links.
  paginateOriginalStyle = true

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  google_verification = ""  # Google_Verification

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []             # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []              # if ['custom.js'], load '/static/js/custom.js' file

  [markup]
      [markup.goldmark]
        [markup.goldmark.renderer]
          unsafe = true

# ------------------------------------- #
# ---- Related Articles --------------- #
# ------------------------------------- #
[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 50

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = true

  # Will lower case keywords in both queries and in the indexes.
  toLower = true

[[related.indices]]
  name = "categories"
  weight = 200

[[related.indices]]
  name = "keywords"
  weight = 150

[[related.indices]]
  name = "tags"
  weight = 100

[languages.en]
  languageCode = "en"
  languageName = "English"
  contentDir = "content/en"
  weight = 2

  [[languages.en.menu.main]]
    name = "Newsletters"
    weight = 10
    identifier = "newsletters"
    url = "category/newsletters/"
  [[languages.en.menu.main]]
    name = "Articles"
    weight = 20
    identifier = "articles"
    url = "category/articles/"
  [[languages.en.menu.main]]
    name = "Projects"
    weight = 30
    identifier = "projects"
    url = "category/projects/"
  [[languages.en.menu.main]]
    name = "Thoughts"
    weight = 40
    identifier = "thoughts"
    url = "category/thoughts/"

  [[languages.en.menu.social]]
    name = "Telegram"
    weight = 10
    identifier = "telegram"
    url = "https://t.me/kohsorbit"
  [[languages.en.menu.social]]
    name = "Twitter"
    weight = 20
    identifier = "twitter"
    url = "https://twitter.com/kohsruhe"
  [[languages.en.menu.social]]
    name = "Instagram"
    weight = 30
    identifier = "instagram"
    url = ""

  [[languages.en.menu.links]]
    name = "Kohs GitHub"
    weight = 10
    identifier = "github"
    url = "https://github.com/leehyon"
  [[languages.en.menu.links]]
    name = "LinkedIn"
    weight = 20
    identifier = "linkedin"
    url = ""
  [[languages.en.menu.links]]
    name = "goodreads"
    weight = 30
    identifier = "goodreads"
    url = "https://www.goodreads.com/leehyon"
  
[languages.zh]
  languageCode = "zh"
  languageName = "中文"
  contentDir = "content/zh"
  weight = 1

  [languages.zh.params]
    description = "When I was seven I thought I had caught the cicada named Summer."

  [[languages.zh.menu.main]]
    name = "周刊"
    weight = 10
    identifier = "newsletters"
    url = "category/newsletters/"
  [[languages.zh.menu.main]]
    name = "文章"
    weight = 20
    identifier = "articles"
    url = "category/articles/"
  [[languages.zh.menu.main]]
    name = "项目"
    weight = 30
    identifier = "projects"
    url = "category/projects/"
  [[languages.zh.menu.main]]
    name = "杂感"
    weight = 40
    identifier = "thoughts"
    url = "category/thoughts/"

  [[languages.zh.menu.social]]
    name = "Telegram"
    weight = 10
    identifier = "telegram"
    url = "https://t.me/kohsorbit"
  [[languages.zh.menu.social]]
    name = "Twitter"
    weight = 20
    identifier = "twitter"
    url = "https://twitter.com/kohsruhe"
  [[languages.zh.menu.social]]
    name = "Instagram"
    weight = 30
    identifier = "instagram"
    url = ""

  [[languages.zh.menu.links]]
    name = "Kohs GitHub"
    weight = 10
    identifier = "github"
    url = "https://github.com/leehyon"
  [[languages.zh.menu.links]]
    name = "LinkedIn"
    weight = 20
    identifier = "linkedin"
    url = ""
  [[languages.zh.menu.links]]
    name = "goodreads"
    weight = 30
    identifier = "goodreads"
    url = "https://www.goodreads.com/leehyon"